### ISSUE TITLE
Registering IMessageHub with MessageHub

### ISSUE THREAD

**Issue by ghost** [NimaAra/Easy.MessageHub#10]
Hi,

Would it be possible to add a public constructor / non singleton implementation of MessageHub? The library seems great, but I would rather use this via the interface and not the static singleton instance.

**Comment by NimaAra** [comment]
This library has been explicitly designed to be a singleton. There is no need to create an instance of the hub.

You can simply register the instance against the `IMessageHub` interface for _IoC Injection_. e.g.:

`container.Register<IMessageHub>(() => MessageHub.Instance);`
