### ISSUE TITLE
Subscribing a runtime type

### ISSUE THREAD

**Issue by odannyc** [NimaAra/Easy.MessageHub#11]
I need to subscribe a runtime type which is defined with an attribute.
For example:
I have class Foo, which I want to subscribe to an Action (non-generic)
That class Foo is defined by an attribute at runtime, meaning I can't do this:

```csharp
Type t = typeof(Foo);
_messageHub.Subscribe<t>({Some method})
```
I know this isn't valid syntax so this won't work.
Is there anyway to make this work?
I was thinking something like this, but not sure if it'll work:
```csharp
Type t = typeof(Foo);
_messageHub.Subscribe(t, {Some method})
```

**Comment by NimaAra** [comment]
I intend to keep the interface generic to avoid boxing but you can use the _GlobalHandler_ in your specific case:

```csharp
hub.RegisterGlobalHandler((type, eventObject) => Console.WriteLine($"Type: {type} - Event: {eventObject}"));
```

**Comment by odannyc** [comment]
This won't work because the event object is not known until the `Publish` phase.

I looked through the code and saw some ways to do it. Can we do this:

Make the Register method:
```csharp
        internal static Guid Register(TimeSpan throttleBy, Action<object> action, Type type)
        {
            var key = Guid.NewGuid();
            var subscription = new Subscription(type, key, throttleBy, action);

            lock (AllSubscriptions)
            {
                AllSubscriptions.Add(subscription);
                _subscriptionsChangeCounter++;
            }

            return key;
        }
```

These would now be the `Subscribe` overloads:

```csharp
public Guid Subscribe<T>(Action<T> action) => Subscribe(action, TimeSpan.Zero, typeof(T));

public Guid Subscribe<T>(Action<T> action, TimeSpan throttleBy) => Subscribe(action, throttleBy, typeof(T));

public Guid Subscribe(Action<object> action, TimeSpan throttleBy, Type type)
{
        EnsureNotNull(action);
        return Subscriptions.Register(throttleBy, action, type);
}
```

**Comment by NimaAra** [comment]
It does work, _RegisterGlobalHandler_ receives every message published. You will have the type as well as the payload.

**Comment by odannyc** [comment]
Okay, just tested and it works just for one `Type`.. I have multiple `Type`s ... So this won't work with my use case.
This is my test code:

```csharp
                _hub.RegisterGlobalHandler((type, eventObject) =>
                {
                    if (type == externalType)
                    {
                        listener.Handle(eventObject);
                    }
                });
```

Each time `RegisterGlobalHandler` is called, it overrides the last one.


Any other way to accomplish this?
What do you think of my suggestion above?

**Comment by NimaAra** [comment]
It does work, I am not going to change the interface (add or remove).

The purpose of _RegisterGlobalHandler_ is to register 1 single handler which will receive every message of every type passed through the hub. It is not meant to build up multiple handlers.

In your case you can compose a handler which knows how to behave based on the types that you are interested in at run-time then register that as the global handler.

```csharp
 _hub.RegisterGlobalHandler((type, eventObject) =>
{
    if (type == firstType)
    {
        // handle eventObj        
    } 
    else if (type == secondType)
    {
        // handle eventObj
    }
    ...
});
```
