### ISSUE TITLE
Publish & Subscribe from different Project?

### ISSUE THREAD

**Issue by VuongVu** [NimaAra/Easy.MessageHub#13]
**Can I use publish & subscribe from 2 projects?**
I write MessageHub functions (have custom publish & subscribe function) to the library(dll) and import into PublishProject and SubscribeProject like this:
`public async Task<Guid> SubscribeMsg(Func<object> MsgFunc)`
`public async Task<bool> PublishMsg(Func<Models.Message> MsgFunc)`

In SubscribeProject, I call the `SubscribeMsg` function of dll and  PublishProject calls the `PublishMsg` function.
SubscribeMsg does not receive msg from MessageHub. Plz tell me my example is right or wrong with your lib? And how can i interact Publish & Subscribe if It call from difference project.
Thanks.

**Comment by NimaAra** [comment]
Please upload a sample of your project to _GitHub_ and I will have a look.

**Comment by NimaAra** [comment]
I am closing this as I haven't heard from you. Feel free to open this backup once you have a sample for me to look at.
