### ISSUE TITLE
How to setup one Server with Many cleints between ASP Core web and .net Console service

### ISSUE THREAD

**Issue by weedkiller** [NimaAra/Easy.MessageHub#17]
Hi, how do I set this up with one ASP Core site (which acts the main hub) and several services and console apps that run as cleints.

I need to ne able exchange commanfs and heart neat

**Comment by NimaAra** [comment]
Hi,

This library is an in-process event aggregator. It seems to me you need a different approach for what you are trying to achieve e.g. _SignalR_ or _GRPC_.
