### ISSUE TITLE
Get MessageHub to play nicely with Autofac in a web application

### ISSUE THREAD

**Issue by inversiondk** [NimaAra/Easy.MessageHub#22]
This lightweight implementation is exactly what I've been looking for for my ASP.NET MVC application. However - I have a hard time figuring out how to use it in a web application setup using AutoFac. 

I can easily publish events to the hub - but my subscribers are never executed. I'm wondering if I'm trying to implement a utility that's not designed for web application use - so I thought I'd get your thoughts on this before proceeding :) 

I have the following simple setup for my AutoFac container: 

```
builder.RegisterInstance<IMessageHub>(new MessageHub());
builder.RegisterType(typeof(PublishStuff)).As<IPublishStuff>().InstancePerLifetimeScope();
builder.RegisterType(typeof(SubscribeToStuff)).As<ISubscribeToStuff>().InstancePerLifetimeScope();
```

And the following setup for publishing / subscribing: 

```
public HomeController(IPublishStuff publishStuff)
{
     _publishStuff = publishStuff;
}

public void TestHub(string message)
{
    _publishStuff.PublishEvent(message);
}
```

And my PublishStuff / SubscribeToStuff: 

```
public class PublishStuff : IPublishStuff
    {
        private readonly IMessageHub _hub;

        public PublishStuff(IMessageHub hub)
        {
            _hub = hub;
        }

        public void PublishEvent(string message)
        {
            _hub.Publish(new UserInviteCreatedEvent { Name = message });
        }
    }


```

```
public class SubscribeToStuff : ISubscribeToStuff
    {
        private readonly IMessageHub _hub;

        public SubscribeToStuff(IMessageHub hub)
        {
            _hub = hub;
            _hub.Subscribe<UserInviteCreatedEvent>(DoStuff);
        }

        public void DoStuff(UserInviteCreatedEvent notification)
        {
            var x = notification.Name;  // <----- THIS IS NEVER EXECUTED
            Debug.WriteLine("The name is " + x);
        }
    }
```

However my SubscribeToStuff remains untouched. The code is never executed. 
AutoFac should be delivering the same instance of the hub every time - but since there's no reference to ISubscribeToStuff anywhere this seems to never be called. 
Is there any trick to getting the hub to play nicely with AutoFac (or another IoC) in a web application setup where the functionality will be spread out across different assemblies etc.? (but initialized from the same web project).
I'm basically looking for the same functionality you'd get from Mediatr Notifications (but without the entire Mediatr setup). 

Thanks a lot - I really enjoy the simplicity of the library you've created :)

**Comment by NimaAra** [comment]
My guess is that you would need to get the lifecycle of the container right. _Easy.MessageHub_ does not care which IoC container or application type is used (as long as registered correctly).

I would suggest posting this on Stackoverflow. Sorry I cannot offer any help.
