### ISSUE TITLE
Support for async actions

### ISSUE THREAD

**Issue by per-ove** [NimaAra/Easy.MessageHub#25]
Hi.
If one for some reason needs to  perform a call to an async method in the  action callback. The global errorhandler does not work because no one await the returned task.
Is it possible to get support for this? 
We can probably surround the async method call in our callback with a try/catch but the global handler are more conveniant to use

**Comment by NimaAra** [comment]
Hi, Thank you for your interest in the library.

There is currently no plan to support async handling in the global handler. The purpose of the global handler is to be light and synchronous.

You can achieve async handling by adding the events to a `Channel<T>` and have other thread(s) consume them asynchronously.

**Comment by per-ove** [comment]
Thank you for your answer. 
I'm happy with that
