### ISSUE TITLE
ThreadLocal(trackAllValues: true) keeps the Values collection growing whenever a new thread is created

### ISSUE THREAD

**Issue by BalintPogatsa** [NimaAra/Easy.MessageHub#27]
If you have a MessageHub for the entire lifetime of your application and threads are being created and terminated, each thread with a Subscription / Unsubscription or Publish will make the ThreadLocal.Values collection to grow.

I've found out the issue with a .NET 4.7 WPF application and Easy.MessageHub version 5.0.0.0

Also ThreadLocal.Values getter started to take longer and longer.
After few days of running, I had 6632 Instances of "Easy.MessageHub.Subscription[]" and calling Unsubscribe took more than a minute.

**Comment by NimaAra** [comment]
Thank you for reporting this. This should now be fixed as of [v5.1.0](https://www.nuget.org/packages/Easy.MessageHub/5.1.0). Can you please give it a try and let me know if this is still an issue.
