### ISSUE TITLE
Support for more profiles?

### ISSUE THREAD

**Issue by ravensorb** [NimaAra/Easy.MessageHub#3]
Any chance of supporting more profiles (PCL, Xamarin, etc) in the nuget package?

**Comment by NimaAra** [comment]
Hi,

I would if I could find the time but not sure when that is going to be. 

If you want to submit a pull request then by all means do so and I will do a release.

Thank you.

**Comment by ravensorb** [comment]
Done -- PR #4

**Comment by NimaAra** [comment]
As of [v3.0.0](https://github.com/NimaAra/Easy.MessageHub/releases/tag/v3.0.0) the library supports _Net 3.5_ and _netstandard1.0_.
