### ISSUE TITLE
Available for dotnet core?

### ISSUE THREAD

**Issue by riker09** [NimaAra/Easy.MessageHub#5]
I'm currently implementing this pattern in one of my services and I was looking for a small library, that does all the hard work while keeping my application small and simple. I came across this project, but I wasn't able to install it via nuget. The error message said, that it is not available for DotNet Core. Is it possible to have this supported?

**Comment by NimaAra** [comment]
Thanks for your interest in the project. 

There is already #3, it is just a matter of finding the time to add support for it and frankly with _.Net Standard 2.0_ still unavailable and terrible tooling experience around _.Net Core_ from _Microsoft_, I will probably leave this until the release of _Visual Studio 2017_ before fully supporting _.Net Core_. Having said that, I may take a look at it this weekend to see how much of a big headache it is going to be.

**Comment by NimaAra** [comment]
As of [v3.0.0](https://github.com/NimaAra/Easy.MessageHub/releases/tag/v3.0.0) the library supports _Net 3.5_ and _netstandard1.0_.
