### ISSUE TITLE
UnSubscribe method causes ArgumentNullException

### ISSUE THREAD

**Issue by GraySerg** [NimaAra/Easy.MessageHub#8]
Field _localSubscriptions is null, if Publish method is not called.
Try to Subscribe, then UnSunbscribe and bang! ArgumentNullException is here.
And it's [ThreadStatic], so on Stop event on windows service it also null.

**Comment by GraySerg** [comment]
Field _localSubscriptions is null, if Publish method is not called.
Try to Subscribe, then UnSunbscribe and bang! ArgumentNullException is here.

**Comment by NimaAra** [comment]
Thanks for the find. This should now be fixed as part of [v3.2.1](https://github.com/NimaAra/Easy.MessageHub/releases/tag/release-v3.2.1) please validate.
